List<Map<String, String>> _brandNames = [
  {"label": " ", "value": ""},
  {"label": "Acm Laboratories", "value": "6362"},
  {"label": "Acqua Di Parma", "value": "6363"},
  {"label": "Aerin", "value": "6364"},
  {"label": "Airval", "value": "6365"},
  {"label": "Armaf", "value": "6366"},
  {"label": "Arteolfatto", "value": "6367"},
  {"label": "Atkinsons", "value": "6368"},
  {"label": "Avène", "value": "6369"},
  {"label": "Azhar Alsaboun", "value": "6370"},
  {"label": "Babybjorn", "value": "6371"},
  {"label": "Babyzen Yoyo", "value": "6372"},
  {"label": "Baobab Collection", "value": "6373"},
  {"label": "Barts", "value": "6374"},
  {"label": "Bath&Body Works", "value": "6375"},
  {"label": "Bdk", "value": "6376"},
  {"label": "Beaba", "value": "6377"},
  {"label": "Bijan", "value": "6378"},
  {"label": "Bill Blass", "value": "6379"},
  {"label": "Bioderma", "value": "6380"},
  {"label": "Boadicea The Victorious", "value": "6381"},
  {"label": "Bobbi Brown", "value": "6382"},
  {"label": "Boon", "value": "6383"},
  {"label": "Bottega Veneta", "value": "6384"},
  {"label": "Brioni", "value": "6385"},
  {"label": "Burberry", "value": "6386"},
  {"label": "Bvlgari", "value": "6387"},
  {"label": "Calvin Klein", "value": "6388"},
  {"label": "Carolina Hererra", "value": "6389"},
  {"label": "Carrera", "value": "6390"},
  {"label": "Cartier", "value": "6391"},
  {"label": "Catrice", "value": "6392"},
  {"label": "Caudalie", "value": "6393"},
  {"label": "Chanel", "value": "6394"},
  {"label": "Clinique", "value": "6395"},
  {"label": "Culti Milano", "value": "6396"},
  {"label": "Cybex", "value": "6397"},
  {"label": "Derby", "value": "6398"},
  {"label": "Dior", "value": "6399"},
  {"label": "Disney", "value": "6400"},
  {"label": "Dockatot", "value": "6401"},
  {"label": "Dr. Vranjes", "value": "6402"},
  {"label": "Elizabeth Arden", "value": "6403"},
  {"label": "Essence", "value": "6404"},
  {"label": "Essie", "value": "6405"},
  {"label": "Estee Lauder", "value": "6406"},
  {"label": "Eveline Cosmetics", "value": "6407"},
  {"label": "Farm Stay", "value": "6408"},
  {"label": "Frank Olivier", "value": "6409"},
  {"label": "Fridababy", "value": "6410"},
  {"label": "Georges Rech", "value": "6411"},
  {"label": "Giorgio Armani", "value": "6412"},
  {"label": "Givenchy", "value": "6413"},
  {"label": "Guerlain", "value": "6414"},
  {"label": "Guess", "value": "6415"},
  {"label": "Hello Kitty", "value": "6416"},
  {"label": "Henbor", "value": "6417"},
  {"label": "Hugo Boss", "value": "6418"},
  {"label": "Infantino", "value": "6419"},
  {"label": "Initio", "value": "6420"},
  {"label": "Invisibobble", "value": "6421"},
  {"label": "Jean Paul Gaultier", "value": "6422"},
  {"label": "Jo Malone London", "value": "6423"},
  {"label": "Jovan", "value": "6424"},
  {"label": "Just For Men", "value": "6425"},
  {"label": "Kerastase", "value": "6426"},
  {"label": "Kevin Murphy", "value": "6427"},
  {"label": "Kiehls", "value": "6428"},
  {"label": "Kryolan", "value": "6429"},
  {"label": "L'Action Paris", "value": "6431"},
  {"label": "L'Objet", "value": "6435"},
  {"label": "Label.M", "value": "6430"},
  {"label": "Lancaster", "value": "6432"},
  {"label": "Lancome", "value": "6433"},
  {"label": "Leonor Greyl", "value": "6434"},
  {"label": "Luminous", "value": "6436"},
  {"label": "Make Up For Ever", "value": "6437"},
  {"label": "Makeup Studio", "value": "6438"},
  {"label": "Malibu", "value": "6439"},
  {"label": "Mamas & Papas", "value": "6440"},
  {"label": "Marvel", "value": "6441"},
  {"label": "Mavala", "value": "6442"},
  {"label": "Moby", "value": "6443"},
  {"label": "My Happy Planet", "value": "6444"},
  {"label": "Napper", "value": "6445"},
  {"label": "Nickelodeon", "value": "6446"},
  {"label": "Nuby", "value": "6447"},
  {"label": "Nuna", "value": "6448"},
  {"label": "Orly", "value": "6449"},
  {"label": "Oskia", "value": "6450"},
  {"label": "Oz Naturals", "value": "6451"},
  {"label": "Paco Rabanne", "value": "6452"},
  {"label": "Pana Dora", "value": "6453"},
  {"label": "Parfums De Marly", "value": "6454"},
  {"label": "Pharmaceris", "value": "6455"},
  {"label": "Philip Kingsley", "value": "6456"},
  {"label": "Potwells", "value": "6457"},
  {"label": "Quut", "value": "6458"},
  {"label": "Ralph Lauren", "value": "6459"},
  {"label": "Revlon", "value": "6460"},
  {"label": "Shnuggle", "value": "6461"},
  {"label": "Svr", "value": "6462"},
  {"label": "The Body Shop", "value": "6463"},
  {"label": "Tommy Hilfiger", "value": "6464"},
  {"label": "Touch Beauty", "value": "6465"},
  {"label": "Twistshake", "value": "6466"},
  {"label": "Uriage", "value": "6467"},
  {"label": "Vagisil", "value": "6468"},
  {"label": "Versace", "value": "6469"},
  {"label": "Vichy", "value": "6470"},
  {"label": "Anastasia Beverly Hills", "value": "6605"},
  {"label": "Anesthesia", "value": "6606"},
  {"label": "Ardell", "value": "6607"},
  {"label": "Beauty Blender", "value": "6608"},
  {"label": "Beesline", "value": "6609"},
  {"label": "Abercrombie & Fitch", "value": "6651"},
  {"label": "Acqua Bambino", "value": "6652"},
  {"label": "Adidas", "value": "6653"},
  {"label": "Adnan.B", "value": "6654"},
  {"label": "Adrienne Vittadini", "value": "6655"},
  {"label": "Afnan", "value": "6656"},
  {"label": "Agent Provocateur", "value": "6657"},
  {"label": "Aigner", "value": "6658"},
  {"label": "Ajmal", "value": "6659"},
  {"label": "Alexander Mqueen", "value": "6660"},
  {"label": "Alexandre-J", "value": "6661"},
  {"label": "Alfred Verne", "value": "6662"},
  {"label": "All Sins 18K", "value": "6663"},
  {"label": "Almas Creation", "value": "6664"},
  {"label": "Alterna", "value": "6665"}
];

String? getBrandNameByValue(String value) {
  for (var item in _brandNames) {
    if (item['value'] == value) {
      return item['label'];
    }
  }
  return null;
}
